MVCData_assignments/Controllers/CountryController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MVCData_assignments.Models.Services;
using MVCData_assignments.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCData_assignments.Controllers
{
    public class CountryController : Controller
    {

        private ICountryService _countryService;
        CountryListViewModel countryListVM = new CountryListViewModel();


        public CountryController(ICountryService countryService)
        {
            _countryService = countryService;
        }

        // GET: CountryController
        public ActionResult Index()
        {
            countryListVM.CountryList = _countryService.GetAll();

            return View(countryListVM);
        }


        // GET: CountryController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CountryController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

    }
}

MVCData_assignments/Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MVCData_assignments.Models;
using MVCData_assignments.Models.Services;

namespace MVCData_assignments.Controllers
{
    public class PersonController : Controller
    {

        private IPersonService _personService;
        PersonListViewModel personListVM = new PersonListViewModel();

        public PersonController(IPersonService personService)
        {
            _personService = personService;
        }

        public IActionResult Index()
        {
            personListVM.PersonList = _personService.GetAll();
            return View(personListVM);
        }


        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(PersonCreateModel personVM)
        {
            if (ModelState.IsValid)
            {
                _personService.Add(personVM);
                return RedirectToAction("Index", personListVM);

            }

            return View("Index", personListVM);
        }
        [HttpPost]
        public IActionResult Update(Person person)
        {
            if (ModelState.IsValid)
            {
                _personService.Edit(person);
                return PartialView("_personPartial", person);

            }

            return View();
        }


        public IActionResult Edit(int id)
        {
            return PartialView("_EditPersonPartial", _personService.GetById(id));
        }


        public IActionResult Delete(int id)
        {
            if (_personService.RemovePerson(id))
            {
                personListVM.PersonList = _personService.GetAll();
                ViewBag.DeleteMsg = "Successfully deleted";
            }
            else ViewBag.DeleteMsg = "Delete failed";
            return View("Index", personListVM);
        }

        [HttpPost]
        public IActionResult Filter(string filter)
        {
            personListVM.Filter = filter;
            personListVM.PersonList = _personService.FilterPerson(filter);
            return View("Index", personListVM);
        }
    }
}

MVCData_assignments/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    @*  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>*@
    <title>@ViewBag.Title</title>

    <style>
        footer {
            left: 0;
            bottom: 0;
            width: 100%;
            position: fixed
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-primary">
            <a class="navbar-brand" href="#">
                <img src="~/img/logo.jpg" alt="Flying pig logo" style="width:60px;" class="navbar-brand" />
            </a>

            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" asp-action="Index" asp-controller="Home">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Index" asp-controller="Person">Person</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Index" asp-controller="Country">Country</a>
                </li>
            </ul>
        </nav>

    </header>
    <div class=" container-fluid bg-light">
        @RenderBody()
    </div>
    <footer class="page-footer pb-3">
        <div class="bg-primary text-center">
            @DateTime.Now.Year Copyright: Gable &copy;
        </div>
    </footer>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>